# Generated by Django 4.2.6 on 2023-11-20 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_categoria_producto_codigo_barra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_codigo',
            field=models.ImageField(blank=True, default='codigos/OIG.png', null=True, upload_to='codigos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_maximo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_introduccion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
