# Generated by Django 4.2.6 on 2023-11-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_producto_categoria_producto_imagen_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuente', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_scraping', to='inventario.producto')),
            ],
        ),
    ]
