# Generated by Django 4.2.6 on 2023-11-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_producto_imagen_codigo_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_codigo',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_productos/'),
        ),
    ]
