# Generated by Django 4.2.6 on 2024-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_remove_producto_imagen_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
