# Generated by Django 4.2.6 on 2024-04-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_tipoproducto_alter_producto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
