# Generated by Django 4.2.6 on 2024-05-01 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_impuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventario.cart'),
        ),
    ]
