# Generated by Django 4.2.6 on 2024-05-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_alter_purchase_cart_purchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='price_at_purchase',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
