# Generated by Django 4.2.6 on 2024-05-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_remove_purchaseitem_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
