# Generated by Django 4.2.6 on 2024-05-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_purchaseitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='impuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.impuesto'),
        ),
    ]
