# Generated by Django 4.2.6 on 2024-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_purchase_impuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono2',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
